open Kanon_kernel

(** Universally checked templates for recursive families.  Templates stay
    outside ordinary globals.  Composition imports explicit dependencies;
    ordinary references to template names remain forbidden. *)
type t

val empty : t
val arity : t -> string -> int option
val members : t -> string -> string list option

(** Companion family names of a template, as the template writes them.
    These names stay template internal: a specialization renames each of
    them.  Send a name through [instance_names] before a global lookup. *)
val companions : t -> string -> string list option
val constructors : t -> string -> string list option

(** Exact family and definition names generated by a specialization.
    A composed template uses [as_name] as a prefix, not a family name.
    Families selected by [reuse] are omitted: they already exist.
    Optional [exports] uses the same complete member-name mapping as
    [instantiate]. An invalid export mapping returns [None], including a
    target equal to a constructor label of the template's families.
    Freshness against ambient globals, ambient constructor labels and
    catalogs is checked by [instantiate]. *)
val instance_names : ?reuse:(string * string) list -> ?exports:(string * string) list ->
  t -> name:string -> as_name:string ->
  (string list * string list) option

(** The result universe must always be Prop or always be Type. Constructor
    names are unique within the family and retain their names in instances.
    Members are definitions checked in order under the symbolic family.
    They may refer to that family and earlier members.  They share its
    universe scope and stay outside the caller's ordinary globals.  A member
    named like a catalog template or like a constructor of an ambient
    family is refused as a collision.  Members are
    traversed first and kernel checked after, so a traversal refusal of a
    later member precedes a kernel refusal of an earlier one. *)
val declare : ?budget:Budget.t -> ?members:Check.decl list -> Global.t -> t -> arity:int ->
  Check.family_decl -> Check.ctor_decl list -> (t, Error.t) result

(** A nonempty ordered group shares one universe scope. Each family may
    refer to earlier families; mutual recursion and forward references are
    refused. Members check after all families. The first family names the
    template and specializes to [as_name]; subsequent families specialize
    to [as_name ^ "_" ^ family_name]. All references are renamed together.
    No symbolic entry escapes and specialization is atomic on failure.
    Members are traversed and kernel checked one at a time in order, so the
    first member that fails either step names the refusal.  That precedence
    differs from [declare], which traverses every member first. *)
val declare_group : ?budget:Budget.t -> ?members:Check.decl list -> Global.t -> t ->
  arity:int -> (Check.family_decl * Check.ctor_decl list) list -> (t, Error.t) result

(** Elaborate ordered members against the checked families and preceding
    checked members.  Each callback returns raw syntax, which is scope
    checked and kernel checked before the next callback runs.  Callbacks
    cannot certify entries or replace the environment.  The catalog is
    returned only after every member succeeds; no callback runs for an
    empty or invalid family group or after an earlier failure.  The first
    member that fails either step names the refusal. *)
val declare_group_elaborated : ?budget:Budget.t ->
  members:(Global.t -> (Check.decl, Error.t) result) list -> Global.t -> t ->
  arity:int -> (Check.family_decl * Check.ctor_decl list) list -> (t, Error.t) result

(** Validate a complete member mapping with the caller's budget before
    surface name planning. The reuse bindings are checked first, in the
    order of [instantiate]: [available] tells which existing family a
    binding may name (the caller's families and the fresh families of
    earlier dependencies), so an unbound reused family is reported as
    [Unbound] before the bindings become name reservations for the
    mapping check. [compose] and [instantiate] check their family
    certificates. *)
val validate_exports : ?budget:Budget.t -> ?reuse:(string * string) list ->
  available:(string -> bool) -> t -> name:string -> as_name:string ->
  (string * string) list -> (unit, Error.t) result

(** Report [Budget_exhausted] when the caller's budget is spent. The
    elaborator polls once between mapping validation and surface name
    planning, so a budget exhausted after the mapping polls still takes
    precedence over a name collision reported by name planning. *)
val poll : Budget.t -> (unit, Error.t) result

(** Compose a nonempty list of preceding family templates.  Each dependency
    is [(template, universe_arguments, local_prefix, reuse, exports)].
    Arguments may use the new group's universe scope. Imported families and definitions are
    renamed, traversed and checked again before the callbacks run.  Members
    see all dependencies and earlier members.  The group name and dependency
    prefixes must be fresh.  Only the complete schema enters the catalog;
    dependency aliases and symbolic globals do not escape.  Nested composed
    templates are flattened in dependency order. Reuse binds local families
    to caller families or families of earlier dependencies. Certificates
    must agree under the full universe scope, and reused families are omitted
    from the new schema. At least one fresh family must remain. Optional
    [exports] names every imported member exactly once, using the same
    validation as [instantiate]. Chosen names are local to the composed
    schema, visible to the group's members, and prefixed
    when the composed schema is specialized. *)
val compose : ?budget:Budget.t ->
  members:(Global.t -> (Check.decl, Error.t) result) list -> Global.t -> t ->
  arity:int -> name:string ->
  (string * Level.t list * string * (string * string) list
    * (string * string) list option) list ->
  (t, Error.t) result

(** Specialize all universe occurrences and self references using exactly
    the declared number of closed levels. Recheck the closed family and
    constructors before returning globals with the fresh instance installed.
    Each member is installed as [as_name ^ "_" ^ member_name], with every
    family and member reference renamed.  Definitions are rechecked in
    order and name collisions are rejected.  Failure leaves both immutable
    input values unchanged. Optional [reuse] binds template-internal family
    names to existing families. Each renamed declaration is kernel checked
    in a temporary table and its complete certificate must match exactly,
    including binder names.  The family level of the certificate is
    compared with the semantic test, so a family level that is not normal
    is accepted.  A closed level argument is normalized once before the
    template is mapped, so a level argument that is not normal is also
    accepted inside the parameter, the index and the constructor
    telescopes, which compare the terms as written.  A closed level above
    the search bound of the normal form keeps its written form and
    refuses the reuse, a conservative answer.  The
    recheck knows the single name of the reused family, so
    a family of a mutual group whose constructor mentions a sibling cannot
    be reused, and the refusal names that cause. Existing families are
    preserved; fresh members recheck against them. Duplicate or unknown
    bindings are refused. Optional [exports] maps every member name exactly
    once to a chosen global name, replacing the default prefixed names.
    Targets must be fresh and distinct from each other, [as_name],
    all installed or reused families, and every constructor label of the
    template's families or of an ambient family. All member references are
    renamed together, including references from later members. *)
val instantiate : ?budget:Budget.t -> ?reuse:(string * string) list ->
  ?exports:(string * string) list ->
  Global.t -> t -> name:string ->
  levels:Level.t list -> as_name:string -> (Global.t, Error.t) result
